### ISSUE TITLE
WHERE I CAN PUT THE TOKENS AND WEEBOOK?

### ISSUE THREAD

**Issue by Nico-ITA** [daaniiieel/discord-telegram-bridge#8]
I dont find a file to put the env!
i cant put tokens or weebook

**Comment by daaniiieel** [comment]
discord-telegram-bridge currently uses env variables, not a file.

**Comment by Nico-ITA** [comment]
i dont understand
can help me joining my ds so we can chat?   https://discord.gg/AkCMTqS

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 25 set 2020 alle ore 16:02 daaniiieel <
notifications@github.com> ha scritto:

**Comment by daaniiieel** [comment]
In the latest release (1.1.3) I added `.env` support. This means that you can **just fill in the deitails in the file named .env** and the program will read from it.
