### ISSUE TITLE
Messages aren't bridged when deployed on hiroku

### ISSUE THREAD

**Issue by ComradDart** [daaniiieel/discord-telegram-bridge#9]
So, messages bridged from telegram to discord, but not bridged from discord to telegram

**Comment by daaniiieel** [comment]
Hey! Are you sure that

- You set every token correctly
- The bot you created is in your discord server
- The bot you created is in your telegram chat?

I'm using it with heroku on a relatively large server (~200 members) without issues

**Comment by ComradDart** [comment]
Ofc all was correct. TediCross works fine for me now, thanks for answer
